### ISSUE TITLE
Code Examples

### ISSUE THREAD

**Issue by gevero** [wsshin/MaxwellFDFD.jl#9]
Are there any examples or tutorials to start using the code? I also would love to contribute with some new examples, but without something to bootstrap the process it's going to be impossible for me.

Best

Giovanni

**Comment by wsshin** [comment]
Sorry, but the lack of examples is intentional: the code is still under development, and I don't think the code is ready for other users yet.  I will add examples and documentation when the code gets mature enough for usage by other users.
